export let defaultSongSequence = [
  // Verse 1: Twinkle, twinkle, little star
  {
    right: {
      finger1: {
        time: 0,
        note: "C4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 0.5,
        note: "C4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 1,
        note: "G4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 1.5,
        note: "G4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 2,
        note: "A4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 0,
        note: "C3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 2,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 1,
        note: "G3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 2,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 2,
        note: "C3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 2.5,
        note: "A4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 3,
        note: "G4",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 4,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 4,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 4,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 3,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 3,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 3,
        note: "G3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 3,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 3,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  // Verse 2: How I wonder what you are
  {
    right: {
      finger1: {
        time: 4,
        note: "F4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 4.5,
        note: "F4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 5,
        note: "E4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 5.5,
        note: "E4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 6,
        note: "D4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 4,
        note: "F3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 6,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 5,
        note: "C3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 6,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 6,
        note: "F3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 6.5,
        note: "D4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 7,
        note: "C4",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 8,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 8,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 8,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 7,
        note: "C3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 7,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 7,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 7,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 7,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  // Verse 3: Up above the world so high
  {
    right: {
      finger1: {
        time: 8,
        note: "G4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 8.5,
        note: "G4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 9,
        note: "F4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 9.5,
        note: "F4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 10,
        note: "E4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 8,
        note: "G3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 10,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 9,
        note: "F3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 10,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 10,
        note: "C3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 10.5,
        note: "E4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 11,
        note: "D4",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 12,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 12,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 12,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 11,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 11,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 11,
        note: "G3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 11,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 11,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  // Verse 4: Like a diamond in the sky
  {
    right: {
      finger1: {
        time: 12,
        note: "G4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 12.5,
        note: "G4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 13,
        note: "F4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 13.5,
        note: "F4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 14,
        note: "E4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 12,
        note: "G3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 14,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 13,
        note: "F3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 14,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 14,
        note: "C3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 14.5,
        note: "E4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 15,
        note: "D4",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 16,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 16,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 16,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 15,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 15,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 15,
        note: "G3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 15,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 15,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  // Outro: Twinkle, twinkle, little star
  {
    right: {
      finger1: {
        time: 16,
        note: "C4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 16.5,
        note: "C4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 17,
        note: "G4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 17.5,
        note: "G4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 18,
        note: "A4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 16,
        note: "C3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 18,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 17,
        note: "G3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 18,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 18,
        note: "C3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 18.5,
        note: "A4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 19,
        note: "G4",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 20,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 20,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 20,
        note: "C4",
        type: "whole",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 19,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger2: {
        time: 19,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 19,
        note: "G3",
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 19,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 20,
        note: "C3",
        type: "whole",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
];
