export let defaultSongSequence = [
  // Twinkle, twinkle, little star
  {
    right: {
      finger1: {
        time: 0,
        note: "C4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 0,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 0,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 0,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 0,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 0,
        note: "C3",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 0,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 0,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 0,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 0,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 1,
        note: "C4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 1,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 1,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 1,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 1,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 1,
        note: "C3",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 1,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 1,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 1,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 1,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 2,
        note: "G4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 2,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 2,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 2,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 2,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 2,
        note: "G3",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 2,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 2,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 2,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 2,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 3,
        note: "G4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 3,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 3,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 3,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 3,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 3,
        note: "G3",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 3,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 3,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 3,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 3,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 4,
        note: "A4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 4,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 4,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 4,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 4,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 4,
        note: "C3",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 4,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 4,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 4,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 4,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 5,
        note: "A4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 5,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 5,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 5,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 5,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 5,
        note: "C3",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 5,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 5,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 5,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 5,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 6,
        note: "G4",
        type: "half",
        pauseBefore: null,
        pauseAfter: "quarter",
      },
      finger2: {
        time: 6,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 6,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 6,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 6,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 6,
        note: "G3",
        type: "half",
        pauseBefore: null,
        pauseAfter: "quarter",
      },
      finger2: {
        time: 6,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 6,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 6,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 6,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  // How I wonder what you are
  {
    right: {
      finger1: {
        time: 8,
        note: "F4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 8,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 8,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 8,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 8,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 8,
        note: "C3",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 8,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 8,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 8,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 8,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 9,
        note: "F4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 9,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 9,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 9,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 9,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 9,
        note: "C3",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 9,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 9,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 9,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 9,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 10,
        note: "E4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 10,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 10,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 10,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 10,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 10,
        note: "G3",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 10,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 10,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 10,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 10,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 11,
        note: "E4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 11,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 11,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 11,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 11,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 11,
        note: "G3",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 11,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 11,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 11,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 11,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 12,
        note: "D4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 12,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 12,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 12,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 12,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 12,
        note: "C3",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 12,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 12,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 12,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 12,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 13,
        note: "D4",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 13,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 13,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 13,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 13,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 13,
        note: "C3",
        type: "quarter",
        pauseBefore: null,
        pauseAfter: "eighth",
      },
      finger2: {
        time: 13,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 13,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 13,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 13,
        note: null,
        type: "quarter",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
  {
    right: {
      finger1: {
        time: 14,
        note: "C4",
        type: "half",
        pauseBefore: null,
        pauseAfter: "quarter",
      },
      finger2: {
        time: 14,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 14,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 14,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 14,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
    left: {
      finger1: {
        time: 14,
        note: "C3",
        type: "half",
        pauseBefore: null,
        pauseAfter: "quarter",
      },
      finger2: {
        time: 14,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger3: {
        time: 14,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger4: {
        time: 14,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
      finger5: {
        time: 14,
        note: null,
        type: "half",
        pauseBefore: null,
        pauseAfter: null,
      },
    },
  },
];
